spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/testquerydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000


logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

# [https://p6spy.readthedocs.io/en/latest/configandusage.html](p6spy_config_guide)
decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
      tracing:
        include-parameter-values: true